### ISSUE TITLE
Can't get LevelExomizer() to work with backward exo crunch

### ISSUE THREAD

**Issue by furroy** [p-a/kickass-cruncher-plugins#5]
I tried to pass in false for first argument to reverse crunch my data but the file seems to come out backward.  Perhaps I don't understand something but my impression was these should produce identical results with exception of offsets added to end of Level. But when I look at the hex of the files in my d64, the bytes are in opposite order.

`
	.modify BackwardMemExomizer(*) {
		* = VIC.COLOR_RAM
		.import binary "assets/gallery/ekat.col"
	}

	.modify LevelExomizer(false, true, true) {
		* = VIC.COLOR_RAM
		.import binary "assets/gallery/ekat.col"
	}
`

**Comment by furroy** [comment]
Pic0c was written with BackwardMemExomizer()
Magic0 was written with LevelExomizer()
[https://i.gyazo.com/0610b09633f76af9e0e567a60a9a4f55.png](url)

**Comment by furroy** [comment]
i think the LevelExomizer() macro is reversing the order of each chunk of data twice when you select backwards crunching. 
```
			if (!opts.containsKey(Options.FORWARD_CRUNCHING)){
				buf = new byte[obj.data.length];
				for(int b = buf.length-1; b >= 0; b--){
					buf[buf.length-1-b] = obj.data[b];
				}

			} else {
				buf = obj.data;
			}
```

i think should just always be buf = obj.data since the data in the crunch object was already reversed, it re-reverses it a second time the way it is now.

**Comment by p-a** [comment]
You may very well be right :) IIRC I struggled quite a bit before getting it right. However, I did like create test cases for all "permutations" and they were fine then at least.
 I don't know how much you've looked into the code, but the crunching is always done by the "raw" cruncher, and then the address/reversing/whatever is appended after.

Question though, are you using the hackish `-DEXOMIZER_COMMANDLINE_FALLBACK` I added since I couldn't get the exo native library to work like before on MacOS?

**Comment by p-a** [comment]
On another note, I've been thinking about abandoning exomizer support. I mean, it is a splendid cruncher, but since I cannot for my life make the native dylib work properly on my mac it is quite hard to maintain. And I did look into make a java-native version, but it was very tough to get it right..

Anyways, the B2 cruncher is really good too.. And a lot fast at decrunching.

**Comment by furroy** [comment]
i did a LevelExomizer() passing in true and false for forward and got same
results both way... calling BackwardsExomizer() made a file always
opposite.  i made that change and the file looks correct on disk, now i
have to redo my code to use the level offsets saved at the end.

i've not tried rebuilding any of the c stuff, i just recompiled the one
class file and injected it into the jar.

i'm on windows 10, not mac, sorry!

R

**Comment by p-a** [comment]
Sorry for being a bit absent. But I actually discovered that the native lib almost magically started working again on my Mac after upgrading to latest jna, and perhaps due to being on catalina.. and jdk11?

I will try and see if I can reproduce what you are experiencing!

**Comment by p-a** [comment]
I have now tested a bit. But AFAICT it really does mimic what the exomizer executable produces.
First now I saw what you first wrote, that use pass in "false" in order to reverse, but that is already the default for level. In fact, I think it is the default behaviour for all exomizer "modes".
But, that's crunching. Then there is the output byte order. And the exomizer doc says

" The level command writes its output file so that the crunched bytes are
returned in correct order for decrunching in the fly while streaming in the
bytes from secondary storage."

Meaning that they are in reversed order if compared to "mem"

Like I said. I remember it was a bit of a hassle understanding the differences between all modes :)

**Comment by furroy** [comment]
Thanks for looking. But I don't understand how passing true and false both give the same output. Surely one of them would opposite of the other?

**Comment by p-a** [comment]
Yes, that's odd. I will have another look :)

**Comment by p-a** [comment]
Sorry, but I checked now, and files matches bit by bit if I compare output with "exomizer level" both forward and normal backwards
